name: Building and testing

on:
  push

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest
    container: hmartin28/mosze:latest
    steps:
      - uses: actions/checkout@v2

      - name: Cppcheck and valgrind
          run: make cppcheck
          run: make valgrind

      - name: Uploading valgrind results
        uses: actions/upload-artifact@v2
        with:
          name: leaklogfile
          path: ./leaklogfile.txt

      - name: Uploading cppcheck results
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_results
          path: ./cppcheckfile.txt

      - name: Diff test
          run: make diff_test