name: Building and testing

on:
  push

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest
    container: hmartin28/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --error-exitcode=1 *.cpp --enable=warning
      - run: cppcheck --output-file=cppcheckfile.txt *.cpp --enable=style,performance
      - run: valgrind --track-origins=yes --leak-check=full --log-file=leaklogfile.txt --error-exitcode=1 ./a.out units/Eivar.json units/Sigurd.json

      - name: Uploading valgrind results
        uses: actions/upload-artifact@v2
        with:
          name: leaklogfile
          path: ./leaklogfile.txt

      - name: Uploading cppcheck results
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_results
          path: ./cppcheckfile.txt

      - run: ./test.sh
      - run: diff results.txt expected_output.txt
