name: Valgrind, cppcheck and diff test

on:
  push

jobs:
  Code test:
    name: Code test
    runs-on: ubuntu-latest
    container: hmartin28/mosze:latest
    steps:
      - uses: actions/checkout@v2

      - name: Run valgrind
        run: make valgrind

      - name: Uploading valgrind results
        uses: actions/upload-artifact@v2
        with:
          name: leaklogfile
          path: ./leaklogfile.txt

      - name: Run cppcheck
        run: make cppcheck

      - name: Uploading cppcheck results
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_results
          path: ./cppcheckfile.txt

  Diff test:
    name: Diff test
    runs-on: ubuntu-latest
    container: hmartin28/mosze:latest
    steps:
      - uses: actions/checkout@v2
        run: make diff_test
