name: JSON Test

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: hmartin28/mosze:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Unit test
        run: make unit_test
